### ISSUE TITLE
Alternative way to create PDF Reports

### ISSUE THREAD

**Issue by allwin199** [Cyfrin/security-and-auditing-full-course-s23#128]
### Discussed in https://github.com/Cyfrin/security-and-auditing-full-course-s23/discussions/126

<div type='discussions-op-text'>

<sup>Originally posted by **allwin199** February 20, 2024</sup>
Vs code Extension: `Markdown PDF`

To create a page with a logo and titles

```js
<!DOCTYPE html>
<html>
<head>
<style>
    .full-page {
        width:  100%;
        height:  100vh; /* This will make the div take up the full viewport height */
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    .full-page img {
        max-width:  200;
        max-height:  200;
        margin-bottom: 5rem;
    }
    .full-page div{
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
</style>
</head>
<body>

<div class="full-page">
    <img src="./logo.svg" alt="Logo">
    <div>
    <h1>Puppy Raffle Protocol Audit Report</h1>
    <h3>Prepared by: Prince Allwin</h3>
    </div>
</div>

</body>
</html>

<!-- Your report starts here! -->
.
.
.
```

[Example of a Report created using this extension](https://github.com/allwin199/puppy-raffle-audit/blob/main/audit-data/report.pdf)

[Example of a Markdown file](https://github.com/allwin199/puppy-raffle-audit/blob/main/audit-data/report.md)

@PatrickAlphaC Is there any downside to this method?

If there is no downside, we can add this to [audit-report-templating](https://github.com/Cyfrin/audit-report-templating) and link it in the [security-and-auditing-full-course-s23 Readme](https://github.com/Cyfrin/security-and-auditing-full-course-s23).</div>

**Comment by PatrickAlphaC** [comment]
@allwin199 this is awesome! Sure, can you add the PR?

**Comment by allwin199** [comment]
Sure!

**Comment by allwin199** [comment]
@PatrickAlphaC Once this [Pull Request](https://github.com/Cyfrin/audit-report-templating/pull/5) gets merged. I will be able to add the details in this repo

**Comment by PatrickAlphaC** [comment]
done !
