### ISSUE TITLE
Should I add the youtube video link here (spot in the description)?

### ISSUE THREAD

**Issue by alymurtazamemon** [Cyfrin/security-and-auditing-full-course-s23#129]
### Describe the enhancement

<img width="690" alt="patrick-security-course" src="https://github.com/Cyfrin/security-and-auditing-full-course-s23/assets/56123405/5b0f00a1-1a69-45d5-9d79-db9263a290d8">

**Comment by PatrickAlphaC** [comment]
This would be great!

Could you also add the bonus NFTs link?

**Comment by PatrickAlphaC** [comment]
We might update them... so actually hold tight

**Comment by PatrickAlphaC** [comment]
This has been updated
