### ISSUE TITLE
section 7: Boss Bridge , Encoding & Decoding link direct to same page

### ISSUE THREAD

**Issue by arifulone** [Cyfrin/security-and-auditing-full-course-s23#145]
### Describe the enhancement

https://github.com/Cyfrin/security-and-auditing-full-course-s23?tab=readme-ov-file#-section-5-invariants--intro-to-defi--tswap-audit:~:text=Encoding%20%26%20Decoding%20Refresher

scroll down to Scoping & Reconnaissance: Boss Bridge

![encoding ](https://github.com/Cyfrin/security-and-auditing-full-course-s23/assets/115061808/1c830053-8b17-41d4-9dd7-f9b91476160a)

**Comment by PatrickAlphaC** [comment]
Did I fix it? I'm not sure what you're trying to describe.

**Comment by arifulone** [comment]
Yes !  now i see ,
 you fix it .
