### ISSUE TITLE
SmallProxy.sol does not compile in Remix without adding a Receive function or using 'hide warnings'.

### ISSUE THREAD

**Issue by 0xTrip** [Cyfrin/security-and-auditing-full-course-s23#161]
### Lesson

Lesson 1

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

https://youtu.be/pUWmJ86X_do?si=xRf3iXmIybjkJTFL&t=6165

### Operating System

Windows

### Describe the bug

At this part of the video, the student is encouraged to play with SmallProxy.sol from: 
https://github.com/Cyfrin/foundry-upgrades-f23/blob/main/src/sublesson/SmallProxy.sol

- A link to this repo could be a good value add, instead of the user searching for it.
- Upon pasting into Remix, contract will not compile until 'hide warnings' is ticked. It may be worth a small comment to inform the user: '// if pasting into Remix, you might need to tick 'hide warnings'

Great course!

**Comment by 0xTrip** [comment]
Ah it seems like I was actually also suffering from a Remix/Chrome issue:
https://ethereum.stackexchange.com/questions/162507/issue-with-accounts-not-displaying-in-remix-vm-cancun-and-shanghai-environment

You are able to deploy the contracts even with the warnings!

**Comment by PatrickAlphaC** [comment]
Great! Closing
