### ISSUE TITLE
Boss Bridge Feedback

### ISSUE THREAD

**Issue by Equious** [Cyfrin/security-and-auditing-full-course-s23#179]
### Describe the enhancement

Arbitrary List:
- The high level coverage of signatures is fine for the purposes of the content, but it leaves quite a few unanswered questions such as the actual definitions and derivations of the `v, r and s` values. Expanding with content focused on signatures would be good!

- MOAR Remix/Vulnerability examples. Seeing the bug in action is awesome.

**Comment by PatrickAlphaC** [comment]
Closing this in favor of the discussions where this was added
