### ISSUE TITLE
Section 2: broken link into the readme.md file 

### ISSUE THREAD

**Issue by 78carla** [Cyfrin/security-and-auditing-full-course-s23#20]
### Describe the enhancement

In the security-and-auditing-full-course-s23 repo: 
- readme.md file 
- Section 2:  What is a smart contract audit 
- Smart Contract Development Life Cycle 
- Is this just one step? This returns a 404 page to me.

**Comment by PatrickAlphaC** [comment]
Are you sure?

https://aws.amazon.com/what-is/sdlc/

This is the link, does this 404?

**Comment by PatrickAlphaC** [comment]
Whoops! Fixed. Thanks!
