### ISSUE TITLE
Yield is spelled "Yeild" throughout section 5

### ISSUE THREAD

**Issue by WillStansill** [Cyfrin/security-and-auditing-full-course-s23#232]
### Lesson

Lesson 5

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

N/A

### Describe the bug

![Screenshot 2024-08-29 130943](https://github.com/user-attachments/assets/fc91ec98-e468-4518-b92e-24db6a137d9c)
In the smart contract security course in section 5 we are consistently using a MockFile that is made called YeildERC20, and its spelled wrong. should be YieldERC20

**Comment by EngrPips** [comment]
Hello @WillStansill, Thanks for this contribution. It will be addressed appropriately as soon as possible.

**Comment by PatrickAlphaC** [comment]
Yeah my bad. Sorry about that.
