### ISSUE TITLE
:adhesive_bandage: wrong Linkedin link in README.md 

### ISSUE THREAD

**Issue by kamikazebr** [Cyfrin/security-and-auditing-full-course-s23#25]
### Describe the enhancement

The [LinkedIn](https://createweb3dapp.alchemy.com/#templates) points to some alchemy link. 

I think that should point to something different related to Linkedin.

**Comment by kamikazebr** [comment]
Just saw that have PR for it #24

**Comment by PatrickAlphaC** [comment]
Yep! Fixed ty
