### ISSUE TITLE
In Section 7, Lesson 22 jumps back to repeat Lesson 8

### ISSUE THREAD

**Issue by 0xk3y** [Cyfrin/security-and-auditing-full-course-s23#26]
### Lesson

Lesson 7

### Describe the bug

In section 7, lesson 22 jumps back to repeat lesson 8 and then proceeds to Lesson 9 instead of Lesson 23.

<img width="215" alt="image" src="https://github.com/Cyfrin/security-and-auditing-full-course-s23/assets/141193328/e1a5c807-d111-4569-8e5f-1c55dbb1482c">

<img width="186" alt="image" src="https://github.com/Cyfrin/security-and-auditing-full-course-s23/assets/141193328/81776171-8097-48f8-a71f-b6cfe7c8a9ed">

**Comment by turvec** [comment]
Experienced the same bug, lesson 22 returns the same path as lesson 8 ".../security/bridges/vault"

**Comment by PatrickAlphaC** [comment]
This should be fixed now, closing
