### ISSUE TITLE
Repeated video in Upgradeable contracts, it is the same as the Encoding function.

### ISSUE THREAD

**Issue by Pol-Gallardo** [Cyfrin/security-and-auditing-full-course-s23#3]
### Lesson

Lesson 1

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

https://www.youtube.com/watch?v=Vy9p6PgNPWg

### Describe the bug

Repeated video in Upgradeable contracts, it is the same as the Encoding function.

**Comment by PatrickAlphaC** [comment]
Fixed, thank you!
