### ISSUE TITLE
Video not uploaded --- Section7 Lesson 13: Signatures Summarized

### ISSUE THREAD

**Issue by libaice** [Cyfrin/security-and-auditing-full-course-s23#35]
### Lesson

Lesson 13

### Could you please leave a link to the timestamp in the video where this error occurs? (You can right click a video and "copy video URL at current time")

https://updraft.cyfrin.io/courses/security/bridges/signatures-summarized

### Describe the bug

This video detail page shows 
```
Network Error
A network error caused the media download to fail.
```

![](https://github.com/Cyfrin/security-and-auditing-full-course-s23/assets/48044642/983e5e45-bb75-4c0e-8dd3-910dc4ea3f0e)

**Comment by PatrickAlphaC** [comment]
Oops! Thanks! We will fix.

**Comment by cromewar** [comment]
Solved!
