### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by moray5554** [Cyfrin/security-and-auditing-full-course-s23#37]
### Describe the bug

It is kinda complicated to work with cyfrin updraft website`s video on half screen mode. You can compare it with Yt - as an opposite i can properly see video in Yt in a same mode. I know i can click the link and open it on Yt as well, but i believe it will be better to do something with UI of website. P.S. Patrick you awesome lecturer <3

**Comment by moray5554** [comment]
![Screenshot from 2023-12-20 13-49-27](https://github.com/Cyfrin/security-and-auditing-full-course-s23/assets/138766838/ead3289f-ff19-4c45-814e-7dbe536859e4)
![Screenshot from 2023-12-20 13-50-00](https://github.com/Cyfrin/security-and-auditing-full-course-s23/assets/138766838/43a9d7dc-80c2-4679-b080-a7c5c89c22eb)

**Comment by PatrickAlphaC** [comment]
Good feedback.. thanks! We'll see how we can fix this.
