### ISSUE TITLE
Disorder of the videos in Review Section

### ISSUE THREAD

**Issue by tahamasood150** [Cyfrin/security-and-auditing-full-course-s23#4]
### Lesson

In The Review section of course

Link: 
https://updraft.cyfrin.io/courses/security/review/upgradeable-contracts

### Describe the bug

In the Review Section, Go towards  'Upgradeable contracts' video & you can see that  It is showing the previous video .
In  'Small proxy' it's showing previous video ''Upgradeable contracts'. Do check it out.

Thanks

**Comment by PatrickAlphaC** [comment]
Thank you! This will be fixed in the next patch
