### ISSUE TITLE
Minor bug: Command line "forge anvil" used instead of "anvil" Lesson 16

### ISSUE THREAD

**Issue by Afriauditor** [Cyfrin/security-and-auditing-full-course-s23#86]
### Lesson

Other (please describe)

### Operating System

Windows

### Describe the bug

\
![Screenshot (60)](https://github.com/Cyfrin/security-and-auditing-full-course-s23/assets/156253299/839b3f8e-0a73-40ca-8f38-89f2901d4d7f)
In the written section of Lesson 16 command line "forge anvil" was written which throws error unrecognized sub-command on terminal. The correct command is "anvil," as accurately demonstrated in the corresponding video section.

**Comment by Equious** [comment]
Good catch. I've adjusted this locally and a PR will be pushed soon to rectify. Thank you!.
